// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpiOFeTZirDZB6XcCvxUtKr7Cquy9OXtc',
    appId: '1:911905811726:web:35aaeb88fa65e88480fb5f',
    messagingSenderId: '911905811726',
    projectId: 'hrm-app-9da14',
    authDomain: 'hrm-app-9da14.firebaseapp.com',
    storageBucket: 'hrm-app-9da14.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtf8MU15wXIy-ULB_3xDVy0-i1O-MPzZ8',
    appId: '1:911905811726:android:8478617a7fedb85780fb5f',
    messagingSenderId: '911905811726',
    projectId: 'hrm-app-9da14',
    storageBucket: 'hrm-app-9da14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaj597-Gw_vUNXe-Q4HECBbAwr0kXft6M',
    appId: '1:911905811726:ios:66c28d355038b68680fb5f',
    messagingSenderId: '911905811726',
    projectId: 'hrm-app-9da14',
    storageBucket: 'hrm-app-9da14.firebasestorage.app',
    iosBundleId: 'com.example.hrmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaj597-Gw_vUNXe-Q4HECBbAwr0kXft6M',
    appId: '1:911905811726:ios:66c28d355038b68680fb5f',
    messagingSenderId: '911905811726',
    projectId: 'hrm-app-9da14',
    storageBucket: 'hrm-app-9da14.firebasestorage.app',
    iosBundleId: 'com.example.hrmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpiOFeTZirDZB6XcCvxUtKr7Cquy9OXtc',
    appId: '1:911905811726:web:c77a0ee9bfdb993280fb5f',
    messagingSenderId: '911905811726',
    projectId: 'hrm-app-9da14',
    authDomain: 'hrm-app-9da14.firebaseapp.com',
    storageBucket: 'hrm-app-9da14.firebasestorage.app',
  );
}
